#!/usr/bin/perl

die "Wrong number of arguments (9 expected). Stopped" unless ($#ARGV == 8);
$sourcehmm = shift(@ARGV);
$targethmm = shift(@ARGV);
$cfgfile   = shift(@ARGV);
$scpfile   = shift(@ARGV);
$alignfile = shift(@ARGV);
$labext	   = shift(@ARGV);
$stcount   = shift(@ARGV);
$modellist = shift(@ARGV);
$logfile   = shift(@ARGV);

$maxpiecesize      = 30000; 	# The exact limit depends on utterance lengths
$MinimumParallel   = 1;		# Minimum number of parallel training processes

###########################################################################

$| = 1; # avoid multiple copies of log messages

print " ...reestimating to $targethmm",`date`;

&run ("cp $sourcehmm $targethmm");

&run("HERest -C $cfgfile -I $alignfile -X $labext ".
	  "-t 250.0 150.0 1000.0 -S $scpfile ".
	  "-H $targethmm -s $stcount $modellist > $logfile");

print " ...finished ",`date`;

###########################################################################

sub run { # run unix shell command with error check
  local($cmd) = @_;
  die "Unix command failed:\n $cmd\n" if system "$cmd";
}

